services:
  mongo:
    image: mongo:latest
    container_name: gigflow_mongo

    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

    healthcheck:
      test: |
        test $$(mongosh --quiet --eval "try { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo:27017' }] }).ok } catch (_) { rs.status().ok }") -eq 1
      interval: 10s
      start_period: 5s

  server:
    build: ./server
    container_name: gigflow_server
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/gigflow?replicaSet=rs0
      - PORT=8000
      - JWT_SECRET=your_super_secret_jwt_key
      - FRONTEND_URL=http://localhost:5173
      - NODE_ENV=development
    depends_on:
      mongo:
        condition: service_healthy

  client:
    build: ./frontend
    container_name: gigflow_client
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000/api
    depends_on:
      - server

volumes:
  mongo-data: